/**
 * Applies the SQL files generated by `pnpm db:generate` into `drizzle/`.
 * Run with `pnpm db:migrate`.
 */
import { migrate } from "drizzle-orm/node-postgres/migrator";

import { logger } from "../lib/logger.ts";
import { db, pool } from "./client.ts";

await migrate(db, { migrationsFolder: new URL("../../drizzle", import.meta.url).pathname });
logger.info("migrations applied");
await pool.end();
